# Change these first
owner: alexanderhodes # Your GitHub organization or username, where this repository lives
repo: upptime-demo # The name of this repository

sites:
  - name: Suite
    url: https://suite.isar-labs.com
    maxResponseTime: 8000
  - name: Construction Documentation
    url: https://construction-documentation.isar-labs.com
    maxResponseTime: 8000
  - name: Document Workflow
    url: https://document-workflow.isar-labs.com
    maxResponseTime: 8000
  - name: Vercel (third party)
    url: https://www.vercel-status.com/api/v2/summary.json
    __dangerous__body_down_if_text_missing: '"indicator":"none"'
    __dangerous__body_degraded: '"indicator":"minor"'
    maxResponseTime: 8000
  - name: Trigger.dev (third party)
    url: https://status.trigger.dev
    __dangerous__body_down_if_text_missing: "All services are online"
    maxResponseTime: 15000
  - name: Neon (third party)
    url: https://neonstatus.com/aws-us-east-n-virginia
    __dangerous__body_down_if_text_missing: "We're fully operational"
    __dangerous__body_degraded_if_text_missing: "operational"
    maxResponseTime: 15000

assignees: # Users to assign downtime issues (optional)
  - alexanderhodes

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.alexanderhodes.de
  #baseUrl: /upptime-demo
  logoUrl: https://raw.githubusercontent.com/alexanderhodes/upptime-demo/refs/heads/master/icon.png
  name: Status
  theme: light
  introTitle: "Das ist die Status-Seite von **Isar Labs**, die auf **Upptime** basiert."
  introMessage: "Hier findest du den aktuellen Status unserer Dienste. Wir arbeiten kontinuierlich daran, eine hohe Verfügbarkeit und Zuverlässigkeit zu gewährleisten."
  navbar:
    - title: Status
      href: /
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"  
