# Change these first
owner: alexanderhodes # Your GitHub organization or username, where this repository lives
repo: upptime-demo # The name of this repository

sites:
#  - name: Google
#    url: https://www.google.com
#  - name: Wikipedia
#    url: https://en.wikipedia.org
#  - name: Hacker News
#    url: https://news.ycombinator.com
  - name: Vercel Status
    url: https://www.vercel-status.com
  - name: Vercel API Status
    url: https://www.vercel-status.com/api/v2/status.json
    expectedStatusCodes:
      - 200
  - name: Vercel System Health
    url: https://www.vercel-status.com/api/v2/summary.json
    __dangerous__body_down_if_text_missing: '"indicator":"none"'
  - name: Vercel Incident Check
    url: https://www.vercel-status.com/api/v2/summary.json  
    __dangerous__body_down: '"indicator":"major"'
  - name: Trigger.dev Status
    url: https://status.trigger.dev
  - name: Trigger.dev Incidents Check
    url: https://status.trigger.dev
    __dangerous__body_down_if_text_missing: "All services are online"
    __dangerous__body_down_if_text_includes: "incident"
    maxResponseTime: 10000
#  - name: Test Broken Site
#    url: https://thissitedoesnotexist.koj.co
#  - name: IPv6 test
#    url: forwardemail.net
#    port: 80
#    check: "tcp-ping"
#    ipv6: true

assignees: # Users to assign downtime issues (optional)
  - alexanderhodes

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-demo
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
